# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "{L/K}"
tagline:             wax poetic
url:                 http://kravinskylev.github.io
paginate:            1
baseurl:             ""

#custom header stuff
pages_list:
  About: '/about'
  Archive: '/archive'
  Connect: '/connect'
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lev Kravinsky
  url:               https://twitter.com/LevKravinsky
  email:             kravinskylev@gmail.com

# Build settings
#markdown: kramdown
markdown: redcarpet

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole
